src/com/hua/hiring/company/entity/CompanyEntity.java
package com.hua.hiring.company.entity;

public class CompanyEntity {
	
	private Integer id;
	private String code;
	private String password;
	private String name;
	private String synopsis;
	private String email;
	private String phone;
	private String linkman;
	private String address;
	private Integer numbers;
	private String slogan;
	 
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getCode() {
		return code;
	}
	public void setCode(String code) {
		this.code = code;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getSynopsis() {
		return synopsis;
	}
	public void setSynopsis(String synopsis) {
		this.synopsis = synopsis;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getLinkman() {
		return linkman;
	}
	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public Integer getNumbers() {
		return numbers;
	}
	public void setNumbers(Integer numbers) {
		this.numbers = numbers;
	}
	public String getSlogan() {
		return slogan;
	}
	public void setSlogan(String slogan) {
		this.slogan = slogan;
	}
	
	
}

src/com/hua/hiring/company/entity/PositionEntity.java
package com.hua.hiring.company.entity;

import java.util.Date;


public class PositionEntity {
	
	private Integer id;
	private Integer companyId;
	private String name;
	private String duty;
	private String ability;
	private Integer salary1;
	private Integer salary2;
	private Date releaseTime;
	
	/**
	 * 扩展属性
	 */
	private String company$name;
	private String company$email;
	private String company$phone;
	private String company$linkman;
	private String company$address;
	private String company$numbers;
	private String company$slogan;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getCompanyId() {
		return companyId;
	}
	public void setCompanyId(Integer companyId) {
		this.companyId = companyId;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDuty() {
		return duty;
	}
	public void setDuty(String duty) {
		this.duty = duty;
	}
	public String getAbility() {
		return ability;
	}
	public void setAbility(String ability) {
		this.ability = ability;
	}
	public Integer getSalary1() {
		return salary1;
	}
	public void setSalary1(Integer salary1) {
		this.salary1 = salary1;
	}
	public Integer getSalary2() {
		return salary2;
	}
	public void setSalary2(Integer salary2) {
		this.salary2 = salary2;
	}
	public Date getReleaseTime() {
		return releaseTime;
	}
	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}
	public String getCompany$name() {
		return company$name;
	}
	public void setCompany$name(String company$name) {
		this.company$name = company$name;
	}
	public String getCompany$address() {
		return company$address;
	}
	public void setCompany$address(String company$address) {
		this.company$address = company$address;
	}
	public String getCompany$slogan() {
		return company$slogan;
	}
	public void setCompany$slogan(String company$slogan) {
		this.company$slogan = company$slogan;
	}
	public String getCompany$email() {
		return company$email;
	}
	public void setCompany$email(String company$email) {
		this.company$email = company$email;
	}
	public String getCompany$phone() {
		return company$phone;
	}
	public void setCompany$phone(String company$phone) {
		this.company$phone = company$phone;
	}
	public String getCompany$linkman() {
		return company$linkman;
	}
	public void setCompany$linkman(String company$linkman) {
		this.company$linkman = company$linkman;
	}
	public String getCompany$numbers() {
		return company$numbers;
	}
	public void setCompany$numbers(String company$numbers) {
		this.company$numbers = company$numbers;
	}
	
}

src/com/hua/hiring/talent/entity/ApplicationEntity.java
package com.hua.hiring.talent.entity;

import java.util.Date;

/**
 * ApplicationEntity
 *
 * @author  刘天印
 * @date  2018年11月24日下午6:55:32
 */
public class ApplicationEntity {
	private Integer id;
	private Integer positionId;
	private Integer talentId;
	private Integer resumeId;
	private Integer status;
	private Date appTime;
	private Date handleTime;
	//扩展
	private String resume$intention;
	private String position$name;
	private Integer company$Id;
	private String company$name;
	private String talent$name;
	
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public Integer getPositionId() {
		return positionId;
	}
	public void setPositionId(Integer positionId) {
		this.positionId = positionId;
	}
	public Integer getTalentId() {
		return talentId;
	}
	public void setTalentId(Integer talentId) {
		this.talentId = talentId;
	}
	public Integer getResumeId() {
		return resumeId;
	}
	public void setResumeId(Integer resumeId) {
		this.resumeId = resumeId;
	}
	public Integer getStatus() {
		return status;
	}
	
	public String getStatusStr() {
		if(status == 1) {
			return "待审核";
		}else if(status == 2) {
			return "审核通过";
		}else if(status == 3) {
			return "已拒绝";
		}
		return "";
	}
	
	public void setStatus(Integer status) {
		this.status = status;
	}
	public Date getAppTime() {
		return appTime;
	}
	public void setAppTime(Date appTime) {
		this.appTime = appTime;
	}
	public Date getHandleTime() {
		return handleTime;
	}
	public void setHandleTime(Date handleTime) {
		this.handleTime = handleTime;
	}
	public String getResume$intention() {
		return resume$intention;
	}
	public void setResume$intention(String resume$intention) {
		this.resume$intention = resume$intention;
	}
	public String getPosition$name() {
		return position$name;
	}
	public void setPosition$name(String position$name) {
		this.position$name = position$name;
	}
	public String getCompany$name() {
		return company$name;
	}
	public void setCompany$name(String company$name) {
		this.company$name = company$name;
	}
	public String getTalent$name() {
		return talent$name;
	}
	public void setTalent$name(String talent$name) {
		this.talent$name = talent$name;
	}
	public Integer getCompany$Id() {
		return company$Id;
	}
	public void setCompany$Id(Integer company$Id) {
		this.company$Id = company$Id;
	}
	
	
}

src/com/hua/hiring/company/servlet/CompanyServlet.java
package com.hua.hiring.company.servlet;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.hua.hiring.common.Constant;
import com.hua.hiring.common.util.AESUtil;
import com.hua.hiring.common.util.AppUtil;
import com.hua.hiring.company.dao.CompanyDao;
import com.hua.hiring.company.entity.CompanyEntity;

public class CompanyServlet extends HttpServlet {
	
	private static final long serialVersionUID = 1L;
	private CompanyDao companyDao = new CompanyDao();
	
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doGet(request, response);
	}

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		String commond = request.getParameter("commond");
		if(commond != null) {
			if("login".equals(commond)){
				login(request, response);
			}else if("logout".equals(commond)){
				logout(request, response);
			}else if("main".equals(commond)){
				main(request, response);
			}else if("register".equals(commond)){
				register(request, response);
			}else if("validateCode".equals(commond)){
				validateCode(request, response);
			}else if("detail".equals(commond)){
				detail(request, response);
			}else if("update".equals(commond)) {
				update(request,response);
			}else if("changePassword".equals(commond)) {
				changePassword(request,response);
			}else{
				throw new IllegalStateException("请求非法");
			}
		}
	}
	/**
	 * 企业登录
	 */
	private void login(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
			//1
			String code = request.getParameter("code");
			String passwordStr = request.getParameter("password");
			String verifyCode = request .getParameter("verifyCode");
			//获取kaptcha生成存放在session中的验证码
	        String kaptchaValue = (String) request.getSession().getAttribute(com.google.code.kaptcha.Constants.KAPTCHA_SESSION_KEY);
			if(verifyCode == null || verifyCode == "") {
				request.setAttribute("errorInfo", "请输入验证码");
				request.getRequestDispatcher("view/company/company-login.jsp").forward(request, response);
			}
			if(!verifyCode.equals(kaptchaValue)) {
				request.setAttribute("errorInfo", "验证码错误，请重新输入验证码");
				request.getRequestDispatcher("view/company/company-login.jsp").forward(request, response);
			}
			//1.3得到相对应的加密密码 
			byte[] passwo = (AESUtil.encrypt(passwordStr,Constant.AES_KEY));
			String password = AESUtil.parseByte2HexStr(passwo);
			//2
			CompanyEntity company = companyDao.login(code,password);
			//3
			if(company == null) {
				request.setAttribute("code", code);
				request.setAttribute("errorInfo", "用户名或密码错误");
				request.getRequestDispatcher("view/company/company-login.jsp").forward(request, response);
			}else {
				request.getSession().setAttribute("company", company);
				//另一个session会话 用于单态登录
				request.getSession().setAttribute("companyCode", code);
				response.sendRedirect("CompanyServlet?commond=main");
				}
	}
	/**
	 * 企业注销
	 */
	private void logout(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		request.getSession().invalidate();
		request.getRequestDispatcher("view/company/company-login.jsp").forward(request, response);
	}
	/**
	 * 企业主页
	 */
	private void main(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		String rowStr = request.getParameter("row");
			//登录时为空
			if (rowStr != null) {
				int row = Integer.parseInt(rowStr);
				if(row == 1){
					request.setAttribute("success", "操作成功~");
				} else {
					request.setAttribute("error", "操作失败~");
				}
			}
		request.getRequestDispatcher("ApplicationServlet?commond=listByCompanyVerifyPage").forward(request, response);
	}
	/**
	 * 企业注册
	 *
	 * @param: @param request
	 * @param: @param response
	 * @param: @throws ServletException
	 * @param: @throws IOException
	 * @return: void
	 * @author: 刘天印
	 * @date: 2018年11月30日 下午7:10:47
	 */
	private void register(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		//1
			String code = request.getParameter("code");
			String password = request.getParameter("password");
			String name = request.getParameter("name");
			String synopsis = request.getParameter("synopsis");
			String phone = request.getParameter("phone");
			String email = request.getParameter("email");
			String linkman = request.getParameter("linkman");
			String address = request.getParameter("address");
			Integer numbers = Integer.parseInt(request.getParameter("numbers"));
			String slogan = request.getParameter("slogan");
		//2
			CompanyEntity companyEntity = new CompanyEntity();
			companyEntity.setCode(code);
			//加密
			byte[] passwo = AESUtil.encrypt(password,Constant.AES_KEY);
			String pass = AESUtil.parseByte2HexStr(passwo);
			companyEntity.setPassword(pass);
			
			companyEntity.setName(name);
			companyEntity.setSynopsis(synopsis);
			companyEntity.setPhone(phone);
			companyEntity.setEmail(email);
			companyEntity.setLinkman(linkman);
			companyEntity.setAddress(address);
			companyEntity.setNumbers(numbers);
			companyEntity.setSlogan(slogan);
			companyDao.regeister(companyEntity);
		
		//3
		request.getRequestDispatcher("view/company/company-login.jsp").forward(request, response);
	}
	/**
	 * 运用AJAX查询了此帐号是否已别占用
	 */
	private void validateCode(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		//1
		String code = request.getParameter("code");
		//2
		CompanyEntity company = companyDao.validateCode(code);
		//3 IO流
		PrintWriter printWriter = response.getWriter();
		try {
			if(company == null) {
				printWriter.print(0);
			}else {
				printWriter.print(1);
			}
		} finally {
			printWriter.close();
		}
}
	/**
	 * 公司的信息（为修改做铺垫）
	 *
	 * @param: @param request
	 * @param: @param response
	 * @param: @throws ServletException
	 * @param: @throws IOException
	 * @return: void
	 * @author: 刘天印
	 * @date: 2018年12月2日 下午3:44:46
	 */
	private void detail(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		int companyId = Integer.parseInt(request.getParameter("id"));
		CompanyEntity company = companyDao.detail(companyId);
		//解密
		byte[] pass = AESUtil.parseHexStr2Byte(company.getPassword());
		byte[] password = AESUtil.decrypt(pass, Constant.AES_KEY);
		company.setPassword(new String(password));
		
		request.setAttribute("company", company);
		request.getRequestDispatcher("view/company/company-info.jsp").forward(request, response);
	}
	/**
	 * 公司信息的修改
	 *
	 * @param: @param request
	 * @param: @param response
	 * @param: @throws ServletException
	 * @param: @throws IOException
	 * @return: void
	 * @author: 刘天印
	 * @date: 2018年12月2日 下午3:58:05
	 */
	private void update(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// 1
		int id = AppUtil.getCompanyId(request, response);
		String code = request.getParameter("code");
		String name = request.getParameter("name");
		String synopsis = request.getParameter("synopsis");
		String email = request.getParameter("email");
		String phone = request.getParameter("phone");
		String linkman = request.getParameter("linkman");
		String address = request.getParameter("address");
		int numbers = Integer.parseInt(request.getParameter("numbers"));
		String slogan = request.getParameter("slogan");
		//
		CompanyEntity companyEntity = new CompanyEntity();
		companyEntity.setId(id);
		companyEntity.setCode(code);
		companyEntity.setName(name);
		companyEntity.setSynopsis(synopsis);
		companyEntity.setEmail(email);
		companyEntity.setPhone(phone);
		companyEntity.setLinkman(linkman);
		companyEntity.setAddress(address);
		companyEntity.setNumbers(numbers);
		companyEntity.setSlogan(slogan);
		int row = companyDao.update(companyEntity);
		// 3
		response.sendRedirect("CompanyServlet?commond=main&row="+ row );
	}
	/**
	 * 
	* @Description: 修改密码
	*
	* @param request
	* @param response
	* @throws ServletException
	* @throws IOException
	* @throws：异常描述
	*
	* @author: 刘天印
	* @date: 2018年12月19日 下午4:48:45 
	*
	 */
	private void changePassword(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		
		int companyId = Integer.parseInt(request.getParameter("id"));
		String passwordStr = request.getParameter("pass"); 
		//加密
		byte[] passwo = AESUtil.encrypt(passwordStr,Constant.AES_KEY);
		String passw = AESUtil.parseByte2HexStr(passwo);
		
		int row = companyDao.changePassword(companyId,passw);
		
		PrintWriter printWriter = response.getWriter();
		try {
			if (row == 1) {
					printWriter.print(1);
				} else {
					printWriter.print(0);
				}
		} finally {
			printWriter.close();
		}
		
	}
}

WebContent/view/company/main.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
	<head>
		<%@ include file="/view/common/header-company.jspf" %>
	</head>
	<body>
		<h1 align="center">企业主页</h1>
		<hr>
		<c:if test="${!empty success || !empty error}">
			<div class="alert alert-warning alert-dismissible" role="alert">
			  	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			  		<span aria-hidden="true">&times;</span>
			  	</button>
			  		<strong>${success }</strong>
			  		<strong>${error }</strong>
			</div>
		</c:if>
		<div class="bs-example" data-example-id="simple-table">
			<table class="table">
				<caption><h3 align="center">一、职位管理</h3></caption>
				<caption>
					<h4 align="center">
						<a href="${ctx }/view/company/position-add.jsp">发布职位</a>
					</h4>
				</caption>
				<thead>
					<tr>
						<th>编号</th>
						<th>职位名称</th>
						<th>薪资</th>
						<th>发布时间</th>
						<th>操作</th>
					</tr>
				</thead>
				<tbody>
					<c:if test="${empty positionList }">
						<tr>
							<td colspan="5" align="center">贵公司还没发布职位呢~！</td>
						</tr>
					</c:if>
					<c:forEach items="${positionList }" var="position" varStatus="v">
						<tr>
							<th scope="row">${v.count }</th>
							<td><a href="${ctx }/PositionServlet?commond=preupdate&id=${position.id}">${position.name }</a></td>
							<td>${position.salary1}--${position.salary2}</td>
							<td><fmt:formatDate value="${position.releaseTime}" pattern="yyyy-MM-dd HH:mm:ss" /></td>
							<td><a href="${ctx }/PositionServlet?commond=delete&id=${position.id}" onclick="return confirm('是否删除？此操作不能恢复')">删除</a>
							</td>
						</tr>
					</c:forEach>
				</tbody>
			</table>
			<table class="table">
				<caption><h3 align="center">二、审核管理</h3></caption>
				<thead>
					<tr>
						<th>编号</th>
						<th>职位名称</th>
						<th>求职者</th>
						<th>简历信息</th>
						<th>审核时间</th>
						<th>审核状态</th>
						<th>操作</th>
					</tr>
					<tr>
						<td colspan="7">
							<form id="submitForm" action="${ctx }/ApplicationServlet?commond=listByCompanyVerifyPage" method="post">
								职位名称：<input type="text" name="positionName" value="${applicationCondition.position$name }">
								审核状态：<select name="status">
										<option value="">-全部-</option>
										<option value="1" <c:if test="${applicationCondition.status == 1 }">selected=selected</c:if>>-待审核-</option>
										<option value="2" <c:if test="${applicationCondition.status == 2 }">selected=selected</c:if>>-已通过-</option>
										<option value="3" <c:if test="${applicationCondition.status == 3 }">selected=selected</c:if>>-已拒绝-</option>
									  </select>
									  
								<button>-查询-</button>
							</form>
						</td>
					</tr>
				</thead>
				<tbody>
					<c:forEach items="${pageModel.list }" var="application" varStatus="v">
						<tr>
							<th scope="row">${v.count }</th>
							<td>${application.position$name }</td>
							<td><a href="javascript:void(0)">${application.talent$name }</a></td>
							<td><a href="javascript:void(0)">${application.resume$intention }</a></td>
							<td><fmt:formatDate value="${application.appTime }" pattern="yyyy-MM-dd HH:mm:ss" type="date"></fmt:formatDate></td>
							<td>
								<c:if test="${application.status == 1 }">
									${application.statusStr }
								</c:if> 
								<c:if test="${application.status == 2 }">
									${application.statusStr }
									(<fmt:formatDate value="${application.handleTime }" pattern="yyyy-MM-dd HH:mm:ss" type="date"></fmt:formatDate>)
								</c:if>
								<c:if test="${application.status == 3 }">
									${application.statusStr }
									(<fmt:formatDate value="${application.handleTime }" pattern="yyyy-MM-dd HH:mm:ss" type="date"></fmt:formatDate>)
								</c:if>
							</td>
							<td><a href="javascript:verify(${application.id },${pageModel.pageNo })">审核</a>
							</td>
						</tr>
					</c:forEach>
					<tr>
						<td colspan="7" align="right">
							<a href="javascript:condition('${ctx }/ApplicationServlet?commond=listByCompanyVerifyPage&pageNo=${pageModel.first}')">首页</a>&nbsp;
							<a href="javascript:condition('${ctx }/ApplicationServlet?commond=listByCompanyVerifyPage&pageNo=${pageModel.pre}')">上一页</a>&nbsp;
							当前第
								<select onchange="goPage(this)">
									<script type="text/javascript">
											var pageNo = '${pageModel.pageNo }';
											var totalPage = '${pageModel.totalPage }';
											for(var x = 1; x <= totalPage; x ++){
												if(pageNo == x){
													document.write('<option value="' + x + '" selected="selected">' + x +'</option>');
												}else{
													document.write('<option value="' + x + '">' + x +'</option>');
												}
											}
									</script>
								</select>页，
							共${pageModel.totalPage }页&nbsp;
							<a href="javascript:condition('${ctx }/ApplicationServlet?commond=listByCompanyVerifyPage&pageNo=${pageModel.next}')">下一页</a>&nbsp;
							<a href="javascript:condition('${ctx }/ApplicationServlet?commond=listByCompanyVerifyPage&pageNo=${pageModel.last}')">尾页</a>&nbsp;
							共${pageModel.allRecords }条记录
						</td>
					</tr>
				</tbody>
			</table>
		</div>
		<%@ include file="/view/common/footer.jspf" %>
		<script>
			/**
			 * 分页的点击事件
			 * @returns
			 */
			function goPage(obj) {
				condition('<%=request.getContextPath()%>/ApplicationServlet?commond=listByCompanyVerifyPage&pageNo=' + obj.value);
			}
			/**
			 *审核状态的点击事件
			 */
			function verify(applicationId,pageNo) {
				
				layer.confirm('通过还是拒绝？', {
					icon: 3,
					btn: ['通过','拒绝'] //按钮
					}, function(){
						layer.msg('您选择了通过~', {icon: 1});
						location = '<%=request.getContextPath()%>/ApplicationServlet?commond=verify&status=2&applicationId=' + applicationId + '&pageNo='+ pageNo ;
					}, function(){
						layer.msg('您选择了拒绝~', {icon: 2});
						location = '<%=request.getContextPath()%>/ApplicationServlet?commond=verify&status=3&applicationId=' + applicationId + '&pageNo='+ pageNo ;
					  });
			}
			/**
			*查询事件：上一页 下一个 首页 尾页
			*/
			function condition(url) {
				var submitForm = document.getElementById('submitForm');
				submitForm.action = url;
				submitForm.submit();
			}
		</script>
		<script src="<%=request.getContextPath() %>/static/common/plugin/layer/layer.js"></script>
	</body>
</html>

WebContent/view/company/position-add.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
	<head>
		<%@ include file="/view/common/header-company.jspf" %>
	</head>
	<body>
		<h1 align="center">发布职位</h1>
		<hr>
		<form action="${ctx }/PositionServlet?commond=add" method="post">
			<div class="form-group">
				<label for="name">职位名称</label> 
				<input type="text" class="form-control" id="name" name="name" placeholder="求职意向">
			</div>
			<div class="form-group">
				<label for="duty">职责说明</label>
				<textarea class="form-control"  rows="5" id="duty" name="duty" placeholder="职责说明"></textarea>
			</div>
			<div class="form-group">
				<label for="ability">能力要求</label>
				<textarea class="form-control" rows="5" id="ability" name="ability" placeholder="能力要求"></textarea>
			</div>
			<div class="form-group">
				<label for="salary1">薪资</label> 
				<input type="text" class="form-control" id="salary1" name="salary1" placeholder="起">-
				<input type="text" class="form-control" id="salary2" name="salary2" placeholder="止">
			</div>
			<button type="submit" class="btn btn-default" style="display:block;margin:0 auto">发布</button>
		</form>
		<%@ include file="/view/common/footer.jspf" %>
	</body>
</html>

WebContent/view/company/position-detail.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link rel="stylesheet" href="<%=request.getContextPath() %>/static/common/plugin/bootstrap-3.3.5/css/bootstrap.min.css">
		<title>职位的详细信息</title>
	</head>
	<body>
		<h1 align="center">职位的详细信息</h1><hr>
		<h2>职位相关信息:</h2><hr>
			职位名称 :${position.name}<br>
			职责说明 :${position.duty}<br>
			能力要求 :${position.ability}<br>
			薪       资 :${position.salary1}--${position.salary2}<br>
			发布时间 :<fmt:formatDate value="${position.releaseTime}" pattern="yyyy-MM-dd HH:mm:ss" /><br>
		<h2>公司相关信息:</h2><hr>
			企业名称 :${position.company$name}<br>
			企业邮箱 :${position.company$email}<br>
			联系电话 :${position.company$phone}<br>
			联  系  人 :${position.company$linkman}<br>
			联系地址 :${position.company$address}<br>
			人       数 :${position.company$numbers}<br>
			服务宗旨 :"${position.company$slogan}"<br>
      		<br>
      	<c:if test="${empty application }">
      		<select id="resume">
      			<option value="">-请选择简历-</option>
      			<c:forEach items="${resumeList }" var="resume">
      				<option value="${resume.id }">${resume.intention }</option>
      			</c:forEach>
      		</select>
	      	<p>
	  			<button type="button" class="btn btn-primary btn-lg" onclick="apply();">投个简历</button>
			</p>
		</c:if>
		<c:if test="${!empty application }">
			<p class="bg-success">该职位已投递，目前审核状态为：${application.statusStr }</p>
		</c:if>
		<button class="btn btn-primary btn-lg" onclick="location='<%=request.getContextPath() %>/PositionServlet?commond=list'">返回首页</button>
		<script src="<%=request.getContextPath() %>/static/common/plugin/jquery.min.js"></script>
		<script src="<%=request.getContextPath() %>/static/common/plugin/bootstrap-3.3.5/js/bootstrap.min.js"></script>
		<script type="text/javascript">
			function apply() {
				var resumeId = document.getElementById('resume').value;
				if(resumeId == ''){
					alert('请先选择简历再进行投递!');
				}else{
					location='<%=request.getContextPath() %>/ApplicationServlet?commond=apply&resumeId=' + resumeId + '&positionId=${position.id}'
				} 
			}
		</script>
	</body>
</html>